const video = [
  {
    id: 1,
    title: "Nova I.A. Cria Qualquer Imagem Através de Texto (é assustador)",
    channel: "Felipe Deschamps",
    views: "9,2 mil visualizaçõess",
    date: "há 5 horas",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Deschamps.webp",
  },
  {
    id: 2,
    title:
      "Nova linhagem do coronavírus pode se espalhar pelo Brasil Band Jornalismo há 1 semana 2 minutos e 1 segundo 982.178 visualizações",
    channel: "Band Jornalismo",
    views: "982 mil visualizaçõess",
    date: "há 1 semana",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Covid.webp",
  },
  {
    id: 3,
    title: "SERÁ QUE NINGUÉM FAZ TESTES AUTOMATIZADOS NO MUNDO REAL?",
    channel: "Erick Wendel",
    views: "4,1 mil",
    date: "há 5 meses",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Wendel.webp",
  },
  {
    id: 4,
    title:
      "Mercado de TI no Canadá - Remuneração e condições de vida, valem a pena?",
    channel: "Micael Mota",
    views: "12 mil",
    date: "há 5 meses",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Micael_canada.webp",
  },
  {
    id: 5,
    title:
      "Mercado de TI no Canadá - Remuneração e condições de vida, valem a pena?",
    channel: "DesignSense",
    views: "80 mil",
    date: "há 2 semanas",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/UI.webp",
  },
  {
    id: 6,
    title: "NEXT.JS: O FRAMEWORK QUE VOCÊ DEVERIA CONHECER",
    channel: "Lucas Nhimi",
    views: "5 mil",
    date: "há 4 meses",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Next.webp",
  },
  {
    id: 7,
    title: "🔴 Let's build LinkedIn with REACT.JS! (with Redux & Firebase)",
    channel: "Sonny Sangha",
    views: "56 mil",
    date: "há 3 semanas",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Sonny.webp",
  },
  {
    id: 8,
    title: "GitHub Universe - Keynote, Dark Mode, Actions Workflow, Palestras e muito mais!",
    channel: "Willian Justen Cursos",
    views: "475 ",
    date: "há 4 semanas",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/WJ.webp",
  },
  {
    id: 9,
    title: "O que é um desenvolvedor Full Cycle?",
    channel: "Full Cycle",
    views: "79 mil",
    date: "há 1 ano",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/FullCycle.webp",
  },
  {
    id: 10,
    title: "React Projects",
    channel: "Coding Addict",
    views: "83 mil",
    date: "há 2 meses",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/React.webp",
  },
  {
    id: 11,
    title: "[BR][Front-End] React - Implementando autenticação de usuários",
    channel: "Matheus Castiglioni",
    views: "14 mil",
    date: "há 1 ano",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/auth.webp",
  },
  {
    id: 12,
    title: "Como implementar uma paginação em ReactJS",
    channel: "Vinicius Dacal",
    views: "191",
    date: "há 11 horas",
    avatar: "/images/avatar.jpeg",
    thumb: "/images/Dacal.webp",
  },
];

export default video